package negocio;
// Generated 08-may-2015 9:34:13 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private SalaId id;
     private String nombre;
     private Short numCama;
     private Set plantillas = new HashSet(0);

    public Sala() {
    }

	
    public Sala(SalaId id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Sala(SalaId id, String nombre, Short numCama, Set plantillas) {
       this.id = id;
       this.nombre = nombre;
       this.numCama = numCama;
       this.plantillas = plantillas;
    }
   
    public SalaId getId() {
        return this.id;
    }
    
    public void setId(SalaId id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Short getNumCama() {
        return this.numCama;
    }
    
    public void setNumCama(Short numCama) {
        this.numCama = numCama;
    }
    public Set getPlantillas() {
        return this.plantillas;
    }
    
    public void setPlantillas(Set plantillas) {
        this.plantillas = plantillas;
    }
}


