package negocio;
// Generated 11-may-2015 12:13:26 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private SalaId id;
     private Hospital hospital;
     private String nombre;
     private Short numCama;
     private Set<Plantilla> plantillas = new HashSet<Plantilla>(0);

    public Sala() {
    }

	
    public Sala(SalaId id, Hospital hospital, String nombre) {
        this.id = id;
        this.hospital = hospital;
        this.nombre = nombre;
    }
    public Sala(SalaId id, Hospital hospital, String nombre, Short numCama, Set<Plantilla> plantillas) {
       this.id = id;
       this.hospital = hospital;
       this.nombre = nombre;
       this.numCama = numCama;
       this.plantillas = plantillas;
    }
   
    public SalaId getId() {
        return this.id;
    }
    
    public void setId(SalaId id) {
        this.id = id;
    }
    public Hospital getHospital() {
        return this.hospital;
    }
    
    public void setHospital(Hospital hospital) {
        this.hospital = hospital;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Short getNumCama() {
        return this.numCama;
    }
    
    public void setNumCama(Short numCama) {
        this.numCama = numCama;
    }
    public Set<Plantilla> getPlantillas() {
        return this.plantillas;
    }
    
    public void setPlantillas(Set<Plantilla> plantillas) {
        this.plantillas = plantillas;
    }




}


